### ISSUE TITLE
lectern still shows as before

### ISSUE THREAD

**Issue by Aces-and-Jacks** [Resourceful-Bees/Highlight#1]
The highlight shows the vanilla highlight

**Comment by ThatGravyBoat** [comment]
I just tested and it worked fine I would suggest checking your mods to make sure its not another mod screwing with it.

**Comment by Aces-and-Jacks** [comment]
Found the mod. It was https://www.curseforge.com/minecraft/mc-mods/resourceful-lib

**Comment by Aces-and-Jacks** [comment]
Though I don't know why I have it since none of my other mods require it as a dependency. I think it's caused by 

> Highlight API (Custom Selection boxes that are not bound to cubes)

**Comment by ThatGravyBoat** [comment]
that is this mods dependency its just inside of it
