### ISSUE TITLE
NeoForge: Invalid Mod File

### ISSUE THREAD

**Issue by LunarDev-git** [Resourceful-Bees/Highlight#9]
Modloader version: 20.5.5
Minecraft Version: 1.20.5

Don't know if this is just because neoforge beta but preferred reporting it 

`invalid mod file net.neoforged.fml.loading.moddiscovery.ModFileInfo@71a3a190
net.neoforged.fml.loading.moddiscovery.InvalidModFileException: Illegal version number specified version (highlight-neoforge-1.20.5-2.5.0.jar)`

**Comment by ThatGravyBoat** [comment]
Fixed in 2.5.1
